### ISSUE TITLE
What about a role for frontend stuff?

### ISSUE THREAD

**Issue by ftassi** [ideatosrl/vagrant-php-template#5]
For a project I've define a frontend role which contains basically 
- nodejs 
- grun-cli

``` yaml
- name: install nodejs deps
  apt: name={{ item }} state=present
  with_items:
    - python-software-properties

- name: add nodejs ppa
  apt_repository: repo=ppa:chris-lea/node.js

- name: Update apt
  apt: update_cache=yes

- name: install PHP5 packages
  apt: name={{ item }} state=latest
  with_items:
    - nodejs

- name: Update NODE_PATH
  lineinfile: dest=/home/vagrant/.zshrc line='export NODE_PATH="$NODE_PATH:./node_modules"'

- npm: name=grunt-cli global=yes
```

Not that much, but may be useful. What would you think about including it in the template? Does `ideato.frontend` make any sense as name?
